package Model;

public class Sunflower extends AbstractPlant {

    private boolean collect;
    private static final int MONEY = 25;

    public Sunflower() {
        super("S", 100, 0, 3, 50);
        this.collect = false;
    }

    /**
     * Generate sun after the counter is 0
     */
    public void generateSun() {
        if (getCounter() == 0) {
            this.setName("C");
            this.setCounter(3);
            this.collect = true;
        }
    }

    /**
     * Collect the sun that is generated and set plant back to normal state.
     *
     * Returns the amount of money generated by the sunflower
     */
    public int collectSun(){
        this.setName("S");
        this.collect = false;
        return MONEY;
    }

    public boolean isCollect() {
        return collect;
    }

    public void setCollect(boolean collect) {
        this.collect = collect;
    }
}
